services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - vp
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  vp:
    name: veripalvelu_default
    external: true
