services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 443:443
    networks:
      - default
      - vp
      - fso
      - rb
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ~/.vps-certificate:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy
      events:
        condition: service_started

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ~/.vps-certificate:/etc/letsencrypt
      - ./certbot.sh:/certbot.sh
      - ~/.cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    entrypoint: /certbot.sh
    # during initialization of a new VPS the certificate is missing
    # and nginx would restart every ~ second
    healthcheck:
      test: ["CMD-SHELL", "test -f /etc/letsencrypt/live/ttj.hu/fullchain.pem"]
      start_period: 2m
      start_interval: 100ms

  # this is a mini-app for a HY course
  events:
    container_name: events
    image: tomjtoth/events
    restart: unless-stopped
    volumes:
      - ./events-data:/app/data

  saldo:
    container_name: saldo
    image: tomjtoth/saldo
    restart: unless-stopped
    volumes:
      - ./saldo-data:/app/data

networks:
  vp:
    name: veripalvelu_default
    external: true

  fso:
    name: fullstack-open_default
    external: true

  rb:
    name: ratebeer_default
    external: true
