services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 443:443
    networks:
      - default
      - vp
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ~/.vps-certificate:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ~/.vps-certificate:/etc/letsencrypt
      - ./certbot.sh:/certbot.sh
      - ~/.cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    entrypoint: /certbot.sh
    # during initialization of a new VPS the certificate is missing
    # and nginx would restart every ~ second
    healthcheck:
      test: ["CMD-SHELL", "test -f /etc/letsencrypt/live/ttj.hu/fullchain.pem"]
      start_period: 2m
      start_interval: 100ms

  saldo:
    container_name: saldo
    image: tomjtoth/saldo
    restart: unless-stopped
    volumes:
      - ./saldo-data:/app/data
      - ~/.env.saldo:/app/.env

  saldo-staging:
    container_name: saldo-staging
    image: tomjtoth/saldo:staging
    restart: unless-stopped
    environment:
      DB_PATH: data/staging.db
      AUTH_URL: https://staging.saldo.ttj.hu/api/auth

    volumes:
      - ./saldo-data:/app/data
      - ~/.env.saldo:/app/.env
    command: >
      sh -c "cp /app/data/prod.db /app/data/staging.db && exec node server.js"

networks:
  vp:
    name: veripalvelu_default
    external: true
