services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - vp
      - fso
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ~/.vps-certificate:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy
      done:
        condition: service_started

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ~/.vps-certificate:/etc/letsencrypt
      - ./certbot.sh:/certbot.sh
      - ~/.cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    entrypoint: /certbot.sh
    healthcheck:
      test: ["CMD-SHELL", "test -f /etc/letsencrypt/live/ttj.hu/fullchain.pem"]
      interval: 5s
      start_period: 0s
      start_interval: 1s
      timeout: 10s
      retries: 12

  # this is a mini-app for a HY course
  done:
    container_name: done
    image: tomjtoth/done
    restart: unless-stopped
    volumes:
      - ./done-data:/app/data

networks:
  vp:
    name: veripalvelu_default
    external: true

  fso:
    name: fullstack-open_default
    external: true
