services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - vp
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./certificate:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy

  certbot:
    image: certbot/dns-cloudflare
    restart: unless-stopped
    volumes:
      - ./certificate:/etc/letsencrypt
      - ./certbot.sh:/certbot.sh
      - ~/.cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    entrypoint: /certbot.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /etc/letsencrypt/live/ttj.hu/fullchain.pem ]"]
      interval: 5s
      start_period: 0s
      start_interval: 1s
      timeout: 10s
      retries: 12

networks:
  vp:
    name: veripalvelu_default
    external: true
