apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  namespace: veripalvelu
  name: veripalvelu-ing

spec:
  ingressClassName: nginx
  rules:
    - host: veripalvelu.ttj.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: veripalvelu-svc
                port:
                  number: 80
