apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ..

patchesStrategicMerge:
  - deployment.yml
  - ingress.yml

namePrefix: staging-

images:
  - name: IMAGES/APP
    newName: tomjtoth/saldo:staging
