apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../prod

patches:
  - path: deployment.yml
  - path: ingress.yml

namePrefix: staging-

images:
  - name: IMAGES/APP
    newName: tomjtoth/saldo:staging
